# Generated by Django 2.1 on 2018-08-19 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('sobrenome', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('login', models.CharField(max_length=30, unique=True)),
                ('senha', models.CharField(max_length=255)),
                ('criacao', models.DateTimeField(auto_now_add=True)),
                ('ativo', models.BooleanField(default=False)),
            ],
        ),
    ]
